-- DROP SCHEMA app;

CREATE SCHEMA app;
-- SPRING_COURSE.app.CUSTOMER definition

-- Drop table

-- DROP TABLE SPRING_COURSE.app.CUSTOMER GO

CREATE TABLE SPRING_COURSE.app.CUSTOMER (
	id int IDENTITY(1,1) NOT NULL,
	first_name varchar(45) COLLATE Modern_Spanish_CI_AS DEFAULT NULL NULL,
	last_name varchar(45) COLLATE Modern_Spanish_CI_AS DEFAULT NULL NULL,
	email varchar(45) COLLATE Modern_Spanish_CI_AS DEFAULT NULL NULL,
	CONSTRAINT PK__CUSTOMER__3213E83F3A7B12DE PRIMARY KEY (id)
) GO;;
